### ISSUE TITLE
vscode 启动插件时 sentry 报错：No hub defined or startTransaction was not found on the hub, please open a bug report

### ISSUE THREAD

**Issue by HayasyLL** [rxliuli/joplin-vscode-plugin#31]
下载插件后，按说明配置好 Joplin WebClipper 的端口、文件夹和Token，

![image](https://user-images.githubusercontent.com/22284698/108653464-75667c80-7501-11eb-9ed9-b3ebe639f692.png)

重启 VSCode，报错如下
```
[2021-02-22 11:22:53.922] [exthost] [error] Activating extension rxliuli.joplin-vscode-plugin failed due to an error:
[2021-02-22 11:22:53.924] [exthost] [error] Error: No hub defined or startTransaction was not found on the hub, please open a bug report.
    at callOnHub (c:\Users\Administrator\.vscode\extensions\rxliuli.joplin-vscode-plugin-0.4.2\node_modules\@sentry\minimal\dist\index.js:20:11)
    at Object.startTransaction (c:\Users\Administrator\.vscode\extensions\rxliuli.joplin-vscode-plugin-0.4.2\node_modules\@sentry\minimal\dist\index.js:206:12)
    at c:\Users\Administrator\.vscode\extensions\rxliuli.joplin-vscode-plugin-0.4.2\out\extension.js:37:36
    at Generator.next (<anonymous>)
    at c:\Users\Administrator\.vscode\extensions\rxliuli.joplin-vscode-plugin-0.4.2\out\extension.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (c:\Users\Administrator\.vscode\extensions\rxliuli.joplin-vscode-plugin-0.4.2\out\extension.js:4:12)
    at activate (c:\Users\Administrator\.vscode\extensions\rxliuli.joplin-vscode-plugin-0.4.2\out\extension.js:36:12)
    at Function._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:13728)
    at Function._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:13405)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:11743
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
```

**Comment by HayasyLL** [comment]
版本：

VSCode: 1.53.2

Joplin: 1.7.11

**Comment by rxliuli** [comment]
> 版本：
> 
> VSCode: 1.53.2
> 
> Joplin: 1.7.11

看起来像是 sentry.io 服务炸了

**Comment by rxliuli** [comment]
> > 版本：
> > VSCode: 1.53.2
> > Joplin: 1.7.11
> 
> 看起来像是 sentry.io 服务炸了

sentry 有大版本更新，今天稍晚一点我改一下，你重启一次 VSCode 看下能否正常使用吧

![image](https://user-images.githubusercontent.com/24560368/108653750-4270b880-7502-11eb-8fad-c93c2ee190eb.png)

**Comment by rxliuli** [comment]
试下预发布的最新版本 v0.4.3 吧

https://github.com/rxliuli/joplin-vscode-plugin/releases/tag/v0.4.3

**Comment by HayasyLL** [comment]
v0.4.3 插件可以正常使用了，谢谢
