### ISSUE TITLE
Running the contributed command: 'joplinNote.openNote' failed.

### ISSUE THREAD

**Issue by akelopes** [rxliuli/joplin-vscode-plugin#32]
I'm getting the following error when trying to open any notes in my list:
```JavaScript
ERR Running the contributed command: 'joplinNote.openNote' failed.: 
Error: Running the contributed command: 'joplinNote.openNote' failed.
	at S._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:103934)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
It was working previously to a reboot. Please let me know what more information you may require and I will provide it.

**Comment by akelopes** [comment]
Problem was with vs code installation in the operating system, it was not recognizing the `code` command configured in the external editor of Joplin settings.
