### ISSUE TITLE
Notes can't be opened when using the joplin snap version

### ISSUE THREAD

**Issue by 3v1n0** [rxliuli/joplin-vscode-plugin#40]
**Describe the bug**

Notes are not opened when using snapped version of joplin-desktop

**To Reproduce**

1. Install `joplin-desktop` from [snap store](https://snapcraft.io/joplin-desktop)
2. Sync notes
3. Open note
4. Nothing is opened:

```
[2021-04-19 14:38:49.930] [renderer3] [error] Running the contributed command: 'joplinNote.openNote' failed.: Error: Running the contributed command: 'joplinNote.openNote' failed.
	at S._executeContributedCommand (/snap/code/62/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106930)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Joplin platform-version: desktop-1.7.11
- VSCode version: 1.55.2
- joplin-vscode-plugin version: 0.4.5

**Further infos**

I've opened a [similar issue in the joplin-desktop snap project](https://github.com/MrCarroll/joplin-desktop-snap/issues/16), as I'm not sure whether the extension is guilty here.

However, it's not clear to me why the binary is involved when opening the notes themselves.

**Comment by rxliuli** [comment]
Project migration: https://github.com/rxliuli/joplin-utils/
